sudo: false
language: go
go: 1.5

branches:
  only:
    - master

install:
  - go get -t ./...
  - go get -u github.com/kisielk/errcheck
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - if ! go get -u github.com/golang/tools/cmd/cover; then go get -u golang.org/x/tools/cmd/cover; fi

script:
  - ./script/test
  - goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
